"""Add nutrition and mental fitness log models

Revision ID: 2ee498e37982
Revises: 5610f35e0f8a
Create Date: 2025-12-01 20:39:56.010976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee498e37982'
down_revision = '5610f35e0f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

