"""Add nutrition and mental fitness log models

Revision ID: 2ee498e37982
Revises: 5610f35e0f8a
Create Date: 2025-12-01 20:39:56.010976

Migration Purpose:
    This migration was generated to add NutritionLog and MentalFitnessLog models,
    but the actual table creation was handled elsewhere (likely via direct SQLAlchemy
    table creation or a previous migration). The upgrade/downgrade functions are empty
    because the schema changes were already applied.

Migration Chain:
    Previous: 5610f35e0f8a (Add conversation messages table)
    Next: e90710938d2d (Add image_path to conversation_messages)

Note:
    Empty migration - tables were created via other means. This migration serves
    as a placeholder in the migration chain to maintain proper ordering.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# revision: Unique identifier for this migration
# down_revision: Previous migration in chain (must match exactly)
revision = '2ee498e37982'
down_revision = '5610f35e0f8a'  # Links to conversation_messages migration
branch_labels = None  # No branch labels (main branch)
depends_on = None  # No external dependencies


def upgrade() -> None:
    """
    Apply migration: Add nutrition and mental fitness log tables.
    
    Note: This migration is empty (pass) because the tables were already created
    via other means. The migration exists to maintain proper ordering in the
    migration chain.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Remove nutrition and mental fitness log tables.
    
    Note: This migration is empty (pass) because the tables were created via
    other means. Rollback would need to be handled manually if required.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

