"""Add conversation messages table

Revision ID: 5610f35e0f8a
Revises: 
Create Date: 2025-12-01 13:02:37.195857

Migration Purpose:
    Creates the conversation_messages table to store chat history between users
    and AI agents. This table tracks messages, roles (user/assistant), content,
    warnings, and timestamps for conversation context.

Table Schema:
    - id: Primary key (auto-increment integer)
    - user_id: Foreign key to users table (required)
    - role: Message role - 'user' or 'assistant' (required)
    - content: Message text content (required, TEXT type for long messages)
    - warnings: Optional warnings from agent (TEXT, nullable)
    - created_at: Timestamp with timezone, defaults to now() (nullable)

Indexes:
    - ix_conversation_messages_id: Index on id column (for lookups)

Foreign Keys:
    - user_id -> users.id: Cascading delete (user deletion removes messages)

Migration Chain:
    This is an early migration (down_revision=None indicates it may be the first
    or one of the first migrations). Later migrations add image_path and agent_type.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5610f35e0f8a'
down_revision = None  # No previous migration (or first in chain)
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Create conversation_messages table.
    
    Creates table with columns for storing chat history:
    - Message content and role (user/assistant)
    - User association via foreign key
    - Warnings from agent responses
    - Timestamp for chronological ordering
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),  # Primary key
    sa.Column('user_id', sa.Integer(), nullable=False),  # Foreign key to users
    sa.Column('role', sa.String(), nullable=False),  # 'user' or 'assistant'
    sa.Column('content', sa.Text(), nullable=False),  # Message content (TEXT for long messages)
    sa.Column('warnings', sa.Text(), nullable=True),  # Optional warnings from agent
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),  # Timestamp with timezone
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),  # Foreign key constraint
    sa.PrimaryKeyConstraint('id')  # Primary key constraint
    )
    # Index on id for faster lookups
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Drop conversation_messages table.
    
    Removes the table and all associated data. This will cascade delete
    any related records (e.g., images referenced by image_path column added later).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')  # Drops table and all data
    # ### end Alembic commands ###

