"""Add image_path to conversation_messages

Revision ID: 624d559258af
Revises: e90710938d2d
Create Date: 2025-12-01 23:21:36.782943

Migration Purpose:
    This migration was intended to add image_path column to conversation_messages,
    but the column was already added by migration e90710938d2d (which comes before
    this in the chain). This migration is empty to maintain proper ordering.

Migration Chain:
    Previous: e90710938d2d (Add image_path to conversation_messages - actual implementation)
    Next: ae8c2903a3db (Add agent_type to conversation_messages)

Note:
    Empty migration - image_path was already added in e90710938d2d. This serves
    as a placeholder in the migration chain. The actual column addition happened
    in the earlier migration.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624d559258af'
down_revision = 'e90710938d2d'  # Links to previous image_path migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Add image_path column to conversation_messages.
    
    Note: This migration is empty (pass) because image_path was already added
    in migration e90710938d2d. This migration exists to maintain proper ordering.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Remove image_path column from conversation_messages.
    
    Note: This migration is empty (pass) because the column addition was handled
    in migration e90710938d2d. Rollback would need to be handled there.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

