"""Add image_path to conversation_messages

Revision ID: 624d559258af
Revises: e90710938d2d
Create Date: 2025-12-01 23:21:36.782943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624d559258af'
down_revision = 'e90710938d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

