"""Add agent_type to conversation_messages

Revision ID: ae8c2903a3db
Revises: 624d559258af
Create Date: 2025-12-02 01:24:22.383509

Migration Purpose:
    Adds agent_type column to conversation_messages table to track which AI agent
    (physical_fitness, nutrition, mental_fitness, coordinator) generated each message.
    This enables filtering conversation history by agent type and routing logic.

Column Details:
    - agent_type: String column (required, NOT NULL)
    - server_default='coordinator': Existing rows get 'coordinator' as default value
      This ensures backward compatibility - existing messages are assumed to be
      from the coordinator agent (which was the only agent initially)

Migration Chain:
    Previous: 624d559258af (Add image_path to conversation_messages)
    Next: f29379640c3d (Add demographics to user_preferences)

Usage:
    Used by GET /conversation/messages?agent_type=nutrition to filter messages
    by specific agent. Also used for agent-specific conversation context.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8c2903a3db'
down_revision = '624d559258af'  # Links to previous image_path migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Add agent_type column to conversation_messages.
    
    Adds column with NOT NULL constraint and default value 'coordinator' for
    existing rows. This ensures all messages have an agent_type assigned.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('agent_type', sa.String(), nullable=False, server_default='coordinator'))
    # agent_type: Required column, defaults to 'coordinator' for existing rows
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Remove agent_type column from conversation_messages.
    
    Drops the column and all agent type data. This will lose the ability to
    filter conversations by agent type.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'agent_type')  # Removes column and data
    # ### end Alembic commands ###

