"""Add agent_type to conversation_messages

Revision ID: ae8c2903a3db
Revises: 624d559258af
Create Date: 2025-12-02 01:24:22.383509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8c2903a3db'
down_revision = '624d559258af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('agent_type', sa.String(), nullable=False, server_default='coordinator'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'agent_type')
    # ### end Alembic commands ###

