"""add_agent_execution_logs_table

Revision ID: e79813599dcb
Revises: f29379640c3d
Create Date: 2025-12-03 05:48:44.405577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79813599dcb'
down_revision = 'f29379640c3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('tools_called', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_execution_logs_agent_type'), 'agent_execution_logs', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_created_at'), 'agent_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_execution_logs_trace_id'), 'agent_execution_logs', ['trace_id'], unique=True)
    op.create_index(op.f('ix_agent_execution_logs_user_id'), 'agent_execution_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_execution_logs_user_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_trace_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_created_at'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_type'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')
    # ### end Alembic commands ###

