"""add_agent_execution_logs_table

Revision ID: e79813599dcb
Revises: f29379640c3d
Create Date: 2025-12-03 05:48:44.405577

Migration Purpose:
    Creates agent_execution_logs table for observability and debugging of AI agent
    executions. Tracks execution metadata including trace IDs, queries, responses,
    tool usage, token consumption, performance metrics, and success/failure status.

Table Schema:
    - id: Primary key (auto-increment integer)
    - trace_id: Unique trace identifier (UUID-like string, UNIQUE index)
    - agent_type: Agent that executed (physical_fitness, nutrition, mental_fitness, coordinator)
    - user_id: Foreign key to users table (required)
    - query: User query text (nullable, TEXT for long queries)
    - response: Agent response text (nullable, TEXT for long responses)
    - warnings: JSON array of warnings from agent (nullable)
    - tools_called: JSON array of tool invocations (nullable)
    - tokens_used: Token count for LLM API call (nullable)
    - duration_ms: Execution duration in milliseconds (nullable, Float for precision)
    - success: Boolean indicating success/failure (nullable)
    - created_at: Timestamp with timezone, defaults to now()

Indexes:
    - trace_id: UNIQUE index (for trace lookups)
    - user_id: Non-unique index (for user-scoped queries)
    - agent_type: Non-unique index (for agent filtering)
    - created_at: Non-unique index (for time-based queries)
    - id: Non-unique index (for primary key lookups)

Foreign Keys:
    - user_id -> users.id: Cascading delete

Usage:
    Used by AgentTracer service to persist execution traces. Enables:
    - Performance monitoring (duration_ms, tokens_used)
    - Debugging (query, response, tools_called)
    - Analytics (success rate, tool usage patterns)
    - API endpoint: GET /agents/execution-logs

Migration Chain:
    Previous: f29379640c3d (Add demographics to user_preferences)
    Next: cd5e821b7af6 (Add performance indexes)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79813599dcb'
down_revision = 'f29379640c3d'  # Links to demographics migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Create agent_execution_logs table.
    
    Creates table with columns for tracking agent execution observability:
    - Trace tracking (trace_id with UNIQUE constraint)
    - Agent identification (agent_type)
    - User association (user_id foreign key)
    - Execution data (query, response, warnings, tools_called)
    - Performance metrics (tokens_used, duration_ms, success)
    - Timestamp for chronological ordering
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),  # Primary key
    sa.Column('trace_id', sa.String(), nullable=False),  # Unique trace identifier
    sa.Column('agent_type', sa.String(), nullable=False),  # Agent type (physical_fitness, nutrition, etc.)
    sa.Column('user_id', sa.Integer(), nullable=False),  # Foreign key to users
    sa.Column('query', sa.Text(), nullable=True),  # User query (TEXT for long queries)
    sa.Column('response', sa.Text(), nullable=True),  # Agent response (TEXT for long responses)
    sa.Column('warnings', sa.JSON(), nullable=True),  # JSON array of warnings
    sa.Column('tools_called', sa.JSON(), nullable=True),  # JSON array of tool invocations
    sa.Column('tokens_used', sa.Integer(), nullable=True),  # Token count for LLM API
    sa.Column('duration_ms', sa.Float(), nullable=True),  # Execution duration (milliseconds, Float for precision)
    sa.Column('success', sa.Boolean(), nullable=True),  # Success/failure status
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),  # Timestamp
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),  # Foreign key constraint
    sa.PrimaryKeyConstraint('id')  # Primary key constraint
    )
    # Indexes for common query patterns
    op.create_index(op.f('ix_agent_execution_logs_agent_type'), 'agent_execution_logs', ['agent_type'], unique=False)  # Filter by agent
    op.create_index(op.f('ix_agent_execution_logs_created_at'), 'agent_execution_logs', ['created_at'], unique=False)  # Time-based queries
    op.create_index(op.f('ix_agent_execution_logs_id'), 'agent_execution_logs', ['id'], unique=False)  # Primary key lookups
    op.create_index(op.f('ix_agent_execution_logs_trace_id'), 'agent_execution_logs', ['trace_id'], unique=True)  # UNIQUE: Trace lookups
    op.create_index(op.f('ix_agent_execution_logs_user_id'), 'agent_execution_logs', ['user_id'], unique=False)  # User-scoped queries
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Drop agent_execution_logs table.
    
    Removes the table and all execution trace data. This will lose all
    observability data including performance metrics and debugging information.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first (required before dropping table)
    op.drop_index(op.f('ix_agent_execution_logs_user_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_trace_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_id'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_created_at'), table_name='agent_execution_logs')
    op.drop_index(op.f('ix_agent_execution_logs_agent_type'), table_name='agent_execution_logs')
    op.drop_table('agent_execution_logs')  # Drops table and all trace data
    # ### end Alembic commands ###

