"""Add image_path to conversation_messages

Revision ID: e90710938d2d
Revises: 2ee498e37982
Create Date: 2025-12-01 23:15:45.737760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90710938d2d'
down_revision = '2ee498e37982'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'image_path')
    # ### end Alembic commands ###

