"""Add image_path to conversation_messages

Revision ID: e90710938d2d
Revises: 2ee498e37982
Create Date: 2025-12-01 23:15:45.737760

Migration Purpose:
    Adds image_path column to conversation_messages table to support image-based
    interactions (e.g., food image analysis via Nutrition Agent with Gemini Vision).
    Stores file system path to uploaded images associated with messages.

Column Details:
    - image_path: String column (nullable, optional)
    - Stores relative file path to image file (e.g., 'images/uuid.jpg')
    - Nullable because most messages don't have images

Migration Chain:
    Previous: 2ee498e37982 (Add nutrition and mental fitness log models)
    Next: 624d559258af (Add image_path to conversation_messages - duplicate/empty)

Usage:
    Used by Nutrition Agent for food image analysis. Images are uploaded via
    POST /conversation/images, stored on file system, and path stored here.
    Images are served via GET /conversation/images/{image_id}.

Note:
    There's a later migration (624d559258af) with the same purpose but empty.
    This migration is the actual implementation.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90710938d2d'
down_revision = '2ee498e37982'  # Links to nutrition/mental fitness logs migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Add image_path column to conversation_messages.
    
    Adds nullable column to store file system path to images associated with
    messages. Used primarily for Nutrition Agent food image analysis.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('image_path', sa.String(), nullable=True))
    # image_path: Optional file path to uploaded image (nullable for messages without images)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Remove image_path column from conversation_messages.
    
    Drops the column. Note: This does NOT delete image files from the file system.
    Image files would need to be cleaned up separately if required.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'image_path')  # Removes column (doesn't delete files)
    # ### end Alembic commands ###

