"""Add demographics to user_preferences

Revision ID: f29379640c3d
Revises: ae8c2903a3db
Create Date: 2025-12-02 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29379640c3d'
down_revision = 'ae8c2903a3db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_preferences', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user_preferences', sa.Column('lifestyle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'lifestyle')
    op.drop_column('user_preferences', 'gender')
    op.drop_column('user_preferences', 'age')
    # ### end Alembic commands ###

