"""Add demographics to user_preferences

Revision ID: f29379640c3d
Revises: ae8c2903a3db
Create Date: 2025-12-02 12:00:00.000000

Migration Purpose:
    Adds demographic columns (age, gender, lifestyle) to user_preferences table
    to enable personalized recommendations from AI agents. These fields help agents
    tailor fitness, nutrition, and wellness advice to user characteristics.

Columns Added:
    - age: Integer (nullable) - User's age in years
    - gender: String (nullable) - User's gender identity
    - lifestyle: String (nullable) - Lifestyle category (e.g., 'sedentary', 'active', 'athletic')

Migration Chain:
    Previous: ae8c2903a3db (Add agent_type to conversation_messages)
    Next: e79813599dcb (Add agent_execution_logs_table)

Usage:
    Used by agents to personalize recommendations:
    - Physical Fitness Agent: Adjusts exercise intensity based on age
    - Nutrition Agent: Tailors meal plans based on age, gender, lifestyle
    - Mental Fitness Agent: Considers lifestyle factors for stress management

All columns are nullable to support gradual data collection (users may not
provide all demographic information immediately).

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29379640c3d'
down_revision = 'ae8c2903a3db'  # Links to agent_type migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply migration: Add demographic columns to user_preferences.
    
    Adds three nullable columns for age, gender, and lifestyle. All columns
    are optional to support gradual data collection from users.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('age', sa.Integer(), nullable=True))  # User age (years)
    op.add_column('user_preferences', sa.Column('gender', sa.String(), nullable=True))  # Gender identity
    op.add_column('user_preferences', sa.Column('lifestyle', sa.String(), nullable=True))  # Lifestyle category
    # All columns nullable - users may not provide all demographic info immediately
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Rollback migration: Remove demographic columns from user_preferences.
    
    Drops all three demographic columns. This will lose personalized
    recommendation capabilities based on demographics.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop in reverse order (not strictly required, but good practice)
    op.drop_column('user_preferences', 'lifestyle')
    op.drop_column('user_preferences', 'gender')
    op.drop_column('user_preferences', 'age')
    # ### end Alembic commands ###

